### ISSUE TITLE
ruby-runtime failed to load w/ java version >= 1.7

### ISSUE THREAD

**Issue by DoCode** [jenkinsci/jenkins.rb#115]
Used by gitlab hook plugin etc.

**Log w/ jre9**
```
May 11, 2015 5:52:32 PM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Loading plugin ruby-runtime
java.io.IOException: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:439)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:371)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42)
	at org.jruby.embed.internal.SingleThreadLocalContextProvider.<init>(SingleThreadLocalContextProvider.java:43)
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:242)
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226)
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:192)
	at org.kohsuke.stapler.jelly.jruby.JRubyFacet.<init>(JRubyFacet.java:65)
	at ruby.RubyRuntimePlugin.registerJRubyFacet(RubyRuntimePlugin.java:39)
	at ruby.RubyRuntimePlugin.start(RubyRuntimePlugin.java:30)
	at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:447)
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:436)
	... 9 more
Caused by: java.lang.RuntimeException: unsupported Java version: 1.9
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1674)
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1387)
	... 19 more
```

**Comment by dkowis** [comment]
This loaded just fine for me on OSx with java 1.8 And on linux boxes with Java 1.8

Maybe just doesn't work in java 1.9 yet.

**Comment by ghost** [comment]
Doesn't work with Java Verions > 1.8. Which is quite bad as 1.8 is already out of support...

**Comment by acasanovass** [comment]
Can confirm that it also doesn't work with OpenJDK 11.
Is there any plan to update it to at least the latest LTS? :D

**Comment by Titaniumtown** [comment]
Yea, I'm getting the error with java 11. This dependency is needed for gitlab integration, seems I'm going back to using a 6 year old JVM again...
