### ISSUE TITLE
jenkins command line tool doesn't work in ruby 2.2.1

### ISSUE THREAD

**Issue by dkowis** [jenkinsci/jenkins.rb#116]
Apparently ther'es some missing dependency or something...? All I did was `gem install jenkins`
```
$ jenkins
/opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/jenkins-0.6.8/lib/jenkins/api.rb:10:in `<top (required)>': uninitialized constant Psych::ENGINE (NameError)
	from /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/jenkins-0.6.8/lib/jenkins.rb:3:in `<module:Jenkins>'
	from /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/jenkins-0.6.8/lib/jenkins.rb:1:in `<top (required)>'
	from /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.1/lib/ruby/gems/2.2.0/gems/jenkins-0.6.8/bin/jenkins:2:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.2.1/bin/jenkins:23:in `load'
	from /opt/boxen/rbenv/versions/2.2.1/bin/jenkins:23:in `<main>'
```

**Comment by dkowis** [comment]
Of note, installing the psych gem didn't help anything :(
