### ISSUE TITLE
Plugin ruby-runtime fails with Java 11

### ISSUE THREAD

**Issue by cesarjorgemartinez** [jenkinsci/jenkins.rb#130]
Jenkins and plugins versions report:
Jenkins 2.303.1 (LTS)
Ruby-runtime 0.12

java -version
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode, sharing)

When start Jenkins: "Failed to initialize"

Then, other dependant plugins don't working

**Comment by mbdevpl** [comment]
I get the same error, latest Jenkins LTS release (2.319.1), latest ruby-runtime plugin version.
```
2021-12-13 05:09:28.318+0000 [id=39]	WARNING	jenkins.model.Jenkins$5#runTask: Loading plugin ruby-runtime v0.12 (ruby-runtime) failed perhaps due to plugin dependency issues
java.lang.RuntimeException: unsupported Java version: 11
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1674)
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1387)
Caused: java.lang.ExceptionInInitializerError
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42)
	at org.jruby.embed.internal.SingleThreadLocalContextProvider.<init>(SingleThreadLocalContextProvider.java:43)
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:242)
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226)
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:192)
	at org.kohsuke.stapler.jelly.jruby.JRubyFacet.<init>(JRubyFacet.java:65)
	at ruby.RubyRuntimePlugin.registerJRubyFacet(RubyRuntimePlugin.java:39)
	at ruby.RubyRuntimePlugin.start(RubyRuntimePlugin.java:30)
	at hudson.ClassicPluginStrategy.startPlugin(ClassicPluginStrategy.java:410)
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:399)
Caused: java.io.IOException: Failed to initialize
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:402)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:536)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

In my case, this affect CI Skip plugin which also fails to load as a result.

**Comment by mbdevpl** [comment]
This looks like a duplicate of: https://github.com/jenkinsci/jenkins.rb/issues/115
